# -*- coding: utf-8 -*-
"""Sistem_Rekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1da3r6HSzN46gxIWmtVBlAC_dyfGboxne

## Import Packages/Library yang digunakan

Di bagian ini, import berbagai library yang akan digunakan dalam proyek ini.

- pandas dan numpy digunakan untuk manipulasi data.
- matplotlib dan seaborn digunakan untuk visualisasi data.
- files digunakan untuk mengunggah file di Google Colab.
"""

import pandas as pd
from google.colab import files
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Loading

### Menunggah kaggle.json
Fungsi `files.upload()` dari Google Colab untuk mengunggah file dataset dari komputer lokal ke lingkungan notebook. Fungsi ini memungkinkan digunakan untuk mengunggah kaggle.json yang ingin digunakan dalam ini.
"""

files.upload()

"""Diperlukan beberapa langkah untuk mengonfigurasi akses ke API Kaggle dan mengunduh dataset yang dibutuhkan untuk proyek ini:

1. **Membuat Direktori untuk API Kaggle:**
   - Perintah `!mkdir ~/.kaggle` digunakan untuk membuat direktori `.kaggle` di lingkungan home pengguna. Direktori ini digunakan untuk menyimpan file kredensial API Kaggle.

2. **Memindahkan File `kaggle.json`:**
   - File `kaggle.json` yang berisi kredensial API dipindahkan ke direktori `.kaggle` menggunakan perintah `!mv kaggle.json ~/.kaggle/`. File ini diperlukan untuk mengautentikasi permintaan ke API Kaggle.

3. **Mengatur Izin Akses File:**
   - Perintah `!chmod 600 ~/.kaggle/kaggle.json` digunakan untuk mengubah izin file `kaggle.json` agar hanya pengguna yang dapat mengaksesnya. Ini meningkatkan keamanan kredensial API.

4. **Mengunduh Dataset dari Kaggle:**
   - Perintah `!kaggle datasets download arashnic/book-recommendation-dataset` digunakan untuk mengunduh dataset "Student Performance for Multiple Linear Regression" dari Kaggle. Dataset ini digunakan untuk tujuan analisis dan pembangunan model regresi linier.

Setelah menjalankan perintah-perintah ini, dataset akan diunduh dan tersedia dalam direktori kerja notebook colab untuk diproses lebih lanjut.
"""

! mkdir ~/.kaggle
! mv kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download arashnic/book-recommendation-dataset

"""Perintah `!unzip` untuk mengekstrak file zip yang baru saja diunduh, yaitu file `book-recommendation-dataset.zip`.

`!unzip /content/book-recommendation-dataset.zip`: Perintah ini akan mengekstrak isi dari file ZIP.

Setelah mengekstrak file, file dataset yang ada di dalamnya, yang berupa file CSV akan digunakan dalam analisis lebih lanjut.
"""

!unzip /content/book-recommendation-dataset.zip

"""Perintah ini menghapus file `book-recommendation-dataset.zip` yang ada di direktori `/content/` untuk menghemat ruang penyimpanan setelah file ZIP tidak lagi dibutuhkan.

Setelah perintah ini dijalankan, file ZIP yang telah diekstrak akan dihapus dari direktori kerja, sehingga hanya file dataset yang diperlukan yang tersisa untuk proses selanjutnya.
"""

!rm /content/book-recommendation-dataset.zip

"""Pada tahap ini, terdapat tiga file CSV yang berisi dataset yang berbeda:
- **Books.csv**: Berisi informasi mengenai buku-buku.
- **Ratings.csv**: Berisi informasi tentang rating yang diberikan oleh pengguna terhadap buku.
- **Users.csv**: Berisi informasi tentang pengguna.

Dengan informasi ini, didapatkan gambaran awal mengenai ukuran dan keberagaman data dalam dataset yang dimiliki.
"""

books = pd.read_csv("/content/Books.csv")
rating = pd.read_csv("/content/Ratings.csv")
users = pd.read_csv("/content/Users.csv")

print(f"Jumlah data user :", len(users['User-ID'].unique()))
print(f"Jumlah data rating :", len(rating))
print(f"Jumlah data books :", len(books['ISBN'].unique()))

"""## Exploratory Data Analysis
Pada tahap ini, dilakukan eksplorasi dataset untuk mendapatkan gambaran umum tentang struktur data dan nilai-nilai yang terkandung di dalamnya.

1. .info() : Memberikan informasi tentang tipe data dan jumlah nilai yang valid di setiap kolom.
2. .head() : Digunakan untuk melihat sekilas beberapa baris pertama dari dataset.

### Book Variabel

Pada cell ini, metode `.info()` pada dataset `books` untuk memperoleh gambaran umum tentang struktur data yang ada pada dataset buku.
"""

books.info()

"""Pada output ini, didapatkan informasi tentang struktur dataset `books` yang berisi 271,360 baris dan 8 kolom.

Dari hasil tersebut, menunjukkan bahwa dataset memiliki 5 kolom, yaitu:
- ISBN: Berisi ID buku yang unik (tipe data: object).
- Book-Title: Menyimpan judul buku (tipe data: object).
- Book-Author: Menyimpan nama penulis buku (tipe data: object).
- Year-Of-Publication: Menyimpan tahun publikasi buku (tipe data: object).
- Publisher: Menyimpan penerbit buku (tipe data: object).
- Image-URL-S : berisi URL gambar sampul buku dalam ukuran S (tipe data: object).
- Image-URL-M : berisi URL gambar sampul buku dalam ukuran M (tipe data: object)
- Image-URL-L : berisi URL gambar sampul buku dalam ukuran L(tipe data: object).
"""

print(f"Jumlah data books :", len(books))

"""### Rating Variabel

Pada cell ini, metode `.info()` pada dataset `rating` untuk memperoleh gambaran umum tentang struktur data yang ada pada dataset rating.
"""

rating.info()

"""Pada output ini, didapatkan informasi tentang struktur dataset `rating` yang berisi 1.149.780 baris dan 3 kolom.

Berikut adalah penjelasan lebih detail terkait hasil yang ditampilkan:
- User-ID : Berisi ID Pengguna yang unik (tipe data: int64).
- ISBN : Berisi ID buku yang unik (tipe data: object).
- Book-Rating : Berisi rating yang diberikan oleh pengguna.

"""

rating.head()

print('Jumlah userID: ', len(users['User-ID'].unique()))
print('Jumlah ISBN: ', len(books.ISBN.unique()))
print('Jumlah data rating: ', len(rating))

"""### User Variabel

Pada cell ini, metode .info() pada dataset `users` untuk memperoleh gambaran umum tentang struktur data yang ada pada dataset users.
"""

users.info()

"""Pada output ini, didapatkan informasi tentang struktur dataset `users` yang berisi 278.858 baris dan 3 kolom.

Berikut adalah penjelasan lebih detail terkait hasil yang ditampilkan:
- User-ID : Berisi ID Pengguna yang unik (tipe data: int64).
- Location : Berisi lokasi geografis pengguna (tipe data: object).
- Age : Berisi usia pengguna (tipe data: float64).
"""

users.head()

"""## Data Preprocessing

Pada tahap ini, dilakukan penggabungan (merge) antara dua DataFrame, yaitu rating dan books. Kedua dataset ini digabungkan berdasarkan kolom ISBN yang menjadi kunci identifikasi buku.

Fungsi **pd.merge()** digunakan untuk menggabungkan dua DataFrame berdasarkan kolom yang memiliki nama yang sama (dalam hal ini, ISBN).

`on='ISBN'` memastikan bahwa penggabungan dilakukan berdasarkan kolom ISBN yang ada di kedua dataset, yaitu dataset buku dan dataset rating.

Proses ini menggabungkan data yang memberikan rating untuk setiap buku dengan informasi lebih lanjut tentang buku tersebut.
"""

data = pd.merge(rating, books, on='ISBN')

data

"""Hasilnya DataFrame baru bernama `data` akan berisi gabungan dari dataset `rating dan `books`. Dengan penggabungan data ini, didapatkan informasi yang lebih lengkap tentang buku yang diberikan rating oleh pengguna.

## Data Preparation

Kode ini memeriksa apakah ada nilai yang hilang dalam dataset menggunakan:

- `data.isnull().sum()`: Menampilkan dan memeriksa jumlah nilai hilang untuk setiap kolom.
"""

data.isnull().sum()

"""Hasilnya ditemukan beberapa kolom dengan missing value :
- `Book-Author` : Ada 2 nilai yang kosong di kolom ini.
- `Publisher` : Ada 2 nilai yang kosong di kolom ini.
- `Image-URL-L` : Ada 4 nilai yang kosong di kolom ini.

Pada kode ini, dilakukan pembersihan data seperti berikut :    

- **Menghapus kolom yang tidak relevan**

  `.drop()` digunakan untuk menghapus kolom yang tidak relevan atau tidak diperlukan dalam analisis lebih lanjut.

- **Menghapus Nilai Kosong**

  `.dropna()` digunakan untuk menghapus baris yang memiliki nilai kosong  di mana pun dalam DataFrame.
"""

data_clean = data.drop(['Year-Of-Publication','Image-URL-S', 'Image-URL-M', 'Image-URL-L'], axis=1).dropna()

data_clean.isnull().sum()

"""Hasil dari kode tersebut :

**Data yang lebih fokus** : Dengan menghapus kolom yang tidak relevan, membuat dataset lebih terfokus pada atribut yang penting untuk rekomendasi.

**Kualitas Data yang Lebih Baik** : Dengan menghapus baris yang memiliki nilai kosong, memastikan bahwa model yang dibangun tidak terpengaruh oleh data yang tidak lengkap.
"""

data_clean

print(f"Number of duplicated: {data_clean.duplicated().sum()}")

"""## Model Development : Content Based Filtering

Tahap ini merupakan pengembangan model berbasis Content-Based Filtering. Dengan menggunakan similarity antara konten buku (pengarang dan penerbit), sistem ini dapat memberikan rekomendasi buku yang relevan berdasarkan buku yang sudah dikenal atau disukai oleh pengguna.

Pada kode ini, memeriksa apakah terdapat karakter non-ASCII dalam nama pengarang buku pada kolom Book-Author. Karakter non-ASCII adalah karakter yang memiliki nilai kode ASCII lebih besar dari 127, seperti karakter dengan aksen atau simbol dari bahasa selain bahasa Inggris.

**Mengubah Kolom menjadi String** :

- `data['Book-Author'].astype(str)`: Mengubah nilai di kolom Book-Author menjadi tipe data string (jika ada nilai yang bukan string atau NaN). Hal ini dilakukan untuk menghindari error saat memproses data non-string.

**Menggunakan apply() untuk Memeriksa Karakter Non-ASCII** :

- `apply(lambda x: any(ord(c) > 127 for c in x))`:  Memeriksa apakah ada karakter dalam nama pengarang yang memiliki kode ASCII lebih besar dari 127, yang menandakan karakter non-ASCII seperti huruf aksen atau simbol dari bahasa lain.

**Menentukan Pengarang dengan Karakter Non-ASCII** :

- `mask` adalah sebuah seri boolean yang menunjukkan apakah suatu baris mengandung karakter non-ASCII atau tidak.
- `weird_authors = data[mask]['Book-Author'].unique()`: Dengan menggunakan masker mask, didapatkan daftar pengarang yang memiliki karakter non-ASCII. `unique()` digunakan untuk mendapatkan hanya nama pengarang yang unik.

Hasil dari proses ini adalah `weird_authors`, yang berisi nama-nama pengarang yang menggunakan karakter non-ASCII dalam nama mereka.
"""

mask = data['Book-Author'].astype(str).apply(lambda x: any(ord(c) > 127 for c in x))
weird_authors = data[mask]['Book-Author'].unique()

"""Pada cell ini terdapat fungsi `normalize_text`:

- `unicodedata.normalize('NFKD', text)` : Fungsi ini mengonversi karakter-karakter Unicode menjadi bentuk dekomposisi Normal Form KC (NFKD), yang memisahkan karakter seperti huruf aksen menjadi dua bagian (misalnya, é menjadi e dan ´).

`.encode('ascii', 'ignore')` : Setelah dekomposisi, teks diubah menjadi format ASCII. Karakter-karakter yang tidak dapat diubah ke format ASCII (seperti é yang menjadi e) akan diabaikan dan tidak disertakan dalam hasil encoding.

`.decode('ascii')` : Setelah encoding, hasilnya diubah kembali menjadi string

**Penerapan Fungsi ke Kolom Book-Author** :

`fillna('')` : Digunakan untuk mengisi nilai NaN di kolom Book-Author dengan string kosong (''), untuk mencegah error pada proses normalisasi.

`astype(str)`: Mengubah seluruh nilai dalam kolom Book-Author menjadi string, jika ada nilai yang tidak berupa string.

`apply(normalize_text)`: Fungsi normalize_text diterapkan ke setiap nilai dalam kolom Book-Author. Ini menghapus karakter non-ASCII dan mengonversinya ke bentuk ASCII standar.

Dengan melakukan normalisasi, kolom Book-Author menjadi lebih konsisten dan standar, yang membuatnya lebih mudah untuk dianalisis atau digunakan dalam model pembelajaran mesin. Ini juga membantu mencegah masalah saat melakukan pemrosesan teks atau analisis berbasis teks. Misalnya, "José" akan menjadi "Jose".
"""

import unicodedata

def normalize_text(text):
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')

# Terapkan ke kolom Book-Author
data_clean['Book-Author'] = data_clean['Book-Author'].fillna('').astype(str)
data_clean['Book-Author'] = data_clean['Book-Author'].apply(normalize_text)

"""Pada langkah ini, **TF-IDF (Term Frequency-Inverse Document Frequency)** digunakan untuk mengekstraksi fitur teks dari kolom **`Book-Author`** dan **`Publisher`**. Tujuan utama dari langkah ini adalah untuk mengubah teks menjadi representasi numerik yang dapat digunakan dalam model pembelajaran mesin.

Kolom `content` dibuat dengan menggabungkan kolom Book-Author dan Publisher. Hal ini memungkinkan untuk mempertimbangkan informasi dari kedua kolom ini saat melakukan ekstraksi fitur. Proses fit pada TfidfVectorizer akan mengidentifikasi kata-kata unik dalam kolom content dan menghitung bobot TF-IDF untuk setiap kata.

- Hasil dari get_feature_names_out() adalah daftar semua kata dan bigram yang dikenali oleh TfidfVectorizer dari kolom content. Setiap fitur ini memiliki bobot yang mencerminkan seberapa penting kata atau bigram tersebut dalam konteks dataset.

- Dengan menggunakan TF-IDF, hal ini dapat memberikan bobot lebih pada kata-kata yang jarang muncul di seluruh dataset namun sering muncul di dokumen tertentu. Hal ini membantu model untuk fokus pada kata-kata yang lebih bermakna dan relevan.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), min_df=2)
data_clean['content'] = data_clean['Book-Author'] + ' ' + data_clean['Publisher']

tf.fit(data_clean['content'])

tf.get_feature_names_out()

"""**cosine similarity** digunakan untuk mengukur kesamaan antar buku berdasarkan konten mereka. Proses ini dilakukan setelah fitur teks diekstraksi menggunakan **TF-IDF**. Dengan cosine similarity, dapat ditentukan seberapa mirip dua buku berdasarkan kombinasi **Book-Author** dan **Publisher** mereka.

- `tf.fit_transform(data_clean['content'])` : Menerapkan TF-IDF pada kolom `content` yang berisi kombinasi Book-Author dan Publisher. Hasilnya adalah tfidf_matrix, yang merupakan representasi numerik dari teks yang diubah menjadi vektor. Setiap vektor ini merepresentasikan satu buku dalam ruang vektor berdasarkan fitur-fitur yang diekstraksi sebelumnya.
- `cosine_similarity(tfidf_matrix)` : Fungsi ini menghitung cosine similarity antara setiap pasangan buku berdasarkan vektor TF-IDF mereka. Nilai cosine similarity berkisar antara 0 (tidak mirip sama sekali) hingga 1 (sangat mirip). Semakin tinggi nilai similarity, semakin mirip dua buku berdasarkan konten mereka.

Cell ini menghasilkan matriks cosine similarity yang menggambarkan seberapa mirip satu buku dengan buku lainnya berdasarkan informasi teks (pengarang dan penerbit). Matriks ini sangat berguna untuk sistem rekomendasi berbasis konten, yang memanfaatkan kesamaan antar buku untuk memberikan saran yang relevan kepada pengguna.
"""

from sklearn.metrics.pairwise import cosine_similarity

data_clean = data_clean.drop_duplicates(subset='Book-Title').head(20000)

tfidf_matrix = tf.fit_transform(data_clean['content'])
cosine_sim = cosine_similarity(tfidf_matrix)

print(cosine_sim[0, :10])

cosine_sim_df = pd.DataFrame(cosine_sim, index=data_clean['Book-Title'], columns=data_clean['Book-Title'])
print('Shape:', cosine_sim_df.shape)

"""Fungsi `book_recommendations` digunakan untuk memberikan rekomendasi buku yang mirip dengan buku yang diberikan oleh pengguna. Rekomendasi dihitung berdasarkan **cosine similarity** yang telah dihitung sebelumnya. Fungsi ini mengambil sebuah **book_title** dan mengembalikan daftar buku yang paling mirip berdasarkan pengukuran similarity.

Fungsi ini mengembalikan DataFrame yang berisi k buku yang paling mirip dengan `book_title` yang diberikan (dalam hal ini k=5). Setiap baris DataFrame berisi informasi terkait buku seperti `Book-Title`, `Book-Author`, dan `Publisher`.
"""

def book_recommendations(book_title, similarity_data=cosine_sim_df, items=data_clean[['Book-Title', 'Book-Author', 'Publisher']], k=5):
    # Mengambil data dengan menggunakan argpartition untuk melakukan partisi secara tidak langsung sepanjang sumbu yang diberikan
    # Dataframe diubah menjadi numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:,book_title].to_numpy().argpartition(
        range(-1, -k, -1))

    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop book_title agar book title yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(book_title, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

book_recommendations('The Notebook')

book_recommendations('Little Men')

"""## Model Development : Collaborative Filtering

Pada tahap ini, dilakukan **encoding** terhadap `User-ID` yang ada dalam dataset agar dapat digunakan dalam model berbasis **Collaborative Filtering**. Proses encoding ini bertujuan untuk mengubah `User-ID` yang berupa kategori menjadi format numerik agar dapat digunakan dalam model pembelajaran mesin.

 Proses encoding ini penting untuk membangun model Collaborative Filtering, karena model ini membutuhkan representasi numerik untuk setiap pengguna dan item (buku dalam hal ini). Dengan encoding ini, model dilatih untuk memprediksi rating pengguna terhadap buku yang belum mereka baca berdasarkan pola preferensi pengguna lain.
"""

# Mengubah userID menjadi list tanpa nilai yang sama
user_ids = data_clean['User-ID'].unique().tolist()
print('list userID: ', user_ids)

# Melakukan encoding userID
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
print('encoded userID : ', user_to_user_encoded)

# Melakukan proses encoding angka ke ke userID
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}
print('encoded angka ke userID: ', user_encoded_to_user)

"""Pada tahap ini, dilakukan **encoding** terhadap `ISBN` (nomor id buku) yang ada dalam dataset agar dapat digunakan dalam model berbasis **Collaborative Filtering**. Proses encoding ini bertujuan untuk mengubah `ISBN` yang berupa kategori menjadi format numerik yang dapat diproses oleh model pembelajaran mesin."""

# Mengubah ISBN menjadi list tanpa nilai yang sama
book_ids = data_clean['ISBN'].unique().tolist()

# Melakukan proses encoding ISBN
book_to_book_encoded = {x: i for i, x in enumerate(book_ids)}

# Melakukan proses encoding angka ke ISBN
book_encoded_to_book = {i: x for i, x in enumerate(book_ids)}

"""Pada tahap ini, dilakukan mapping `User-ID` dan `ISBN` yang ada dalam dataset ke bentuk numerik yang sudah dilakukan encoding sebelumnya.

Proses mapping ini memungkinkan untuk mengganti ID pengguna dan ISBN buku yang semula berupa string atau kategori menjadi representasi numerik. Ini sangat penting untuk model Collaborative Filtering yang mengandalkan data numerik untuk melakukan perhitungan interaksi pengguna dengan item (buku). Selanjutnya, dapat menggunakan kolom user dan book untuk melatih model dan melakukan prediksi rating secara efektif.
"""

# Mapping userID ke dataframe user
data_clean['user'] = data_clean['User-ID'].map(user_to_user_encoded)

# Mapping ISBN ke dataframe book
data_clean['book'] = data_clean['ISBN'].map(book_to_book_encoded)

# Mendapatkan jumlah user
num_users = len(user_to_user_encoded)
print(num_users)

# Mendapatkan jumlah book
num_book = len(book_encoded_to_book)
print(num_book)

# Mengubah rating menjadi nilai float
data_clean['Book-Rating'] = data_clean['Book-Rating'].values.astype(np.float32)

# Nilai minimum rating
min_rating = min(data_clean['Book-Rating'])

# Nilai maksimal rating
max_rating = max(data_clean['Book-Rating'])

print('Number of User: {}, Number of Book: {}, Min Rating: {}, Max Rating: {}'.format(
    num_users, num_book, min_rating, max_rating
))

df = data_clean.sample(frac=1, random_state=42)
df

"""Pada tahap ini, data dipersiapkan untuk melatih model dengan cara memisahkan fitur dan target dari dataset. Selain itu, juga membagi data menjadi dua bagian: **data pelatihan (train)** dan **data validasi (validation)**. Data dibagi menjadi dua bagian: 80% untuk pelatihan (train) dan 20% untuk validasi (validation).

Fitur `x` mengandung data yang menjelaskan siapa yang memberi rating pada buku tertentu, sedangkan target `y` berisi rating yang diberikan.
"""

# Membuat variabel x untuk mencocokkan data user dan book menjadi satu value
x = df[['user', 'book']].values

# Membuat variabel y untuk membuat rating dari hasil
y = df['Book-Rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values

# Membagi menjadi 80% data train dan 20% data validasi
train_indices = int(0.8 * df.shape[0])
x_train, x_val, y_train, y_val = (
    x[:train_indices],
    x[train_indices:],
    y[:train_indices],
    y[train_indices:]
)

print(x, y)

"""Model **RecommenderNet** menggunakan pendekatan Collaborative Filtering. Ini adalah model yang digunakan untuk memprediksi rating atau preferensi pengguna terhadap buku, yang memungkinkan sistem untuk memberikan rekomendasi buku berdasarkan interaksi pengguna sebelumnya.

Model ini memberikan prediksi rating antara pengguna dan buku dalam rentang [0, 1]. Rating yang diprediksi ini dapat digunakan untuk memberikan rekomendasi buku kepada pengguna berdasarkan preferensi mereka yang dipelajari oleh model.
"""

from tensorflow.keras import layers
from tensorflow import keras
import tensorflow as tf

class RecommenderNet(tf.keras.Model):

  # Insialisasi fungsi
  def __init__(self, num_users, num_book, embedding_size, **kwargs):
    super(RecommenderNet, self).__init__(**kwargs)
    self.num_users = num_users
    self.num_book = num_book
    self.embedding_size = embedding_size
    self.user_embedding = layers.Embedding( # layer embedding user
        num_users,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.user_bias = layers.Embedding(num_users, 1) # layer embedding user bias
    self.book_embedding = layers.Embedding( # layer embeddings book
        num_book,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.book_bias = layers.Embedding(num_book, 1) # layer embedding book bias

  def call(self, inputs):
    user_vector = self.user_embedding(inputs[:,0]) # memanggil layer embedding 1
    user_bias = self.user_bias(inputs[:, 0]) # memanggil layer embedding 2
    book_vector = self.book_embedding(inputs[:, 1]) # memanggil layer embedding 3
    book_bias = self.book_bias(inputs[:, 1]) # memanggil layer embedding 4

    dot_user_book = tf.tensordot(user_vector, book_vector, 2)

    x = dot_user_book + user_bias + book_bias

    return tf.nn.sigmoid(x) # activation sigmoid

"""Model siap untuk dilatih, dengan loss function dan optimizer yang telah dipilih sesuai dengan tugas rekomendasi yang ingin diselesaikan.

Model dikompilasi menggunakan `MeanSquaredError` sebagai loss function dan `Adam` sebagai optimizer. `RootMeanSquaredError` digunakan sebagai metrik untuk mengevaluasi kinerja model.
"""

model = RecommenderNet(num_users, num_book, 50) # inisialisasi model

# model compile
model.compile(
    loss= tf.keras.losses.MeanSquaredError(),
    optimizer = keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

"""Pada tahap ini, ditambahkan **EarlyStopping** sebagai callback dalam pelatihan model.

**EarlyStopping** digunakan untuk menghentikan pelatihan jika model tidak menunjukkan perbaikan yang signifikan setelah sejumlah epoch tertentu (dalam hal ini, 3 epoch berturut-turut).

Fungsi `monitor='val_root_mean_squared_error'` menunjukkan bahwa model akan memonitor metrik Root Mean Squared Error (RMSE) pada data validasi (validation set) untuk menghentikan pelatihan lebih awal jika model tidak menunjukkan peningkatan.

`patience=3` berarti pelatihan akan dihentikan jika model tidak menunjukkan perbaikan selama 3 epoch berturut-turut.

`restore_best_weights=True` memastikan bahwa bobot model yang terbaik (dengan nilai RMSE terendah di data validasi) akan dipulihkan setelah pelatihan dihentikan, sehingga model yang digunakan adalah model yang paling optimal.
"""

early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_root_mean_squared_error', # Monitor RMSE di validation set
    patience=3,
    restore_best_weights=True
)

"""Pada tahap ini, model dilatih menggunakan data training (x_train, y_train) dengan parameter yang sudah ditentukan sebelumnya.

Model akan dilatih selama 100 epoch atau lebih sedikit jika EarlyStopping menghentikan pelatihan lebih awal.

Setelah setiap epoch, model akan menghitung nilai loss dan Root Mean Squared Error (RMSE) untuk data training dan data validasi.

Dengan menggunakan EarlyStopping, jika model tidak menunjukkan perbaikan pada data validasi setelah 3 epoch berturut-turut, pelatihan akan dihentikan lebih awal dan model terbaik berdasarkan performa di data validasi akan dipulihkan.

Hasil dari pelatihan disimpan dalam variabel history, yang berisi informasi mengenai loss dan RMSE pada setiap epoch, baik untuk data training maupun validasi. Hal ini memungkinkan untuk memantau kemajuan pelatihan dan performa model seiring berjalannya waktu.
"""

history = model.fit(
    x = x_train,
    y = y_train,
    batch_size = 32,
    callbacks = [early_stopping],
    epochs = 100,
    validation_data = (x_val, y_val)
)

"""Pada tahap ini, dilakukan memvisualisasikan perkembangan Root Mean Squared Error (RMSE) selama proses pelatihan untuk data training dan validasi. Visualisasi ini membantu kita untuk mengevaluasi seberapa baik model berperforma dan apakah ada tanda-tanda overfitting atau underfitting."""

plt.plot(history.history['root_mean_squared_error'])
plt.plot(history.history['val_root_mean_squared_error'])
plt.title('model_metrics')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

user_id = df['User-ID'].sample(1).iloc[0]
book_visited_by_user = df[df['User-ID'] == user_id]

book_not_visited = books[~books['ISBN'].isin(book_visited_by_user.ISBN.values)]['ISBN']
book_not_visited = list(
    set(book_not_visited)
    .intersection(set(book_to_book_encoded.keys()))
)

book_not_visited = [[book_to_book_encoded.get(x)] for x in book_not_visited]
user_encoder = user_to_user_encoded.get(user_id)
user_book_array = np.hstack(
    ([[user_encoder]] * len(book_not_visited), book_not_visited)
)

"""**Menampilkan Rekomendasi Buku untuk Pengguna**

Pada cell ini, menampilkan hasil rekomendasi dari model yang telah dilatih untuk memprediksi rating untuk setiap buku yang belum dikunjungi oleh pengguna yang dipilih.

**Buku Berdasarkan Rating Pengguna** : Buku yang sudah pernah dinilai oleh pengguna ditampilkan terlebih dahulu, diurutkan berdasarkan rating yang tertinggi. Ini memberikan gambaran mengenai preferensi pengguna terhadap buku.

**Rekomendasi Buku Baru Berdasarkan Prediksi** : 10 buku baru yang belum dinilai oleh pengguna tetapi diprediksi akan disukai berdasarkan pola preferensi pengguna sebelumnya ditampilkan sebagai rekomendasi.
"""

ratings = model.predict(user_book_array).flatten()

top_ratings_indices = ratings.argsort()[-10:][::-1]
recommended_book_ids = [
    book_encoded_to_book.get(book_not_visited[x][0]) for x in top_ratings_indices
]

print('Showing recommendations for users: {}'.format(user_id))
print('===' * 9)
print('Book with high ratings from user')
print('----' * 8)

top_book_user = (
    book_visited_by_user.sort_values(
        by = 'Book-Rating',
        ascending=False
    )
    .head(5)
    .ISBN.values
)

book_df_rows = books[books['ISBN'].isin(top_book_user)]

for index, row in book_df_rows.iterrows():
  print(row['Book-Title'], ':', row['Book-Author'], '-', row['Publisher'])

print('----' * 8)
print('Top 10 Books recommendation')
print('----' * 8)

recommended_book = books[books['ISBN'].isin(recommended_book_ids)]
for index, row in recommended_book.iterrows():
  print(row['Book-Title'], ':', row['Book-Author'], '-', row['Publisher'])

"""Hasil yang ditampilkan mencakup:
- Buku yang sudah pernah dinilai oleh pengguna dengan rating tertinggi.
- Buku-buku baru yang direkomendasikan berdasarkan prediksi rating.
"""